name: Check barber availability

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check availability
        run: bash check.sh
        env:
          BRR_SECRET_KEY: ${{ secrets.BRR_SECRET_KEY }}
